### ISSUE TITLE
bug 提交

### ISSUE THREAD

**Issue by kyohan789** [LG-leige/open_cloud#1]
1，https://github.com/LG-leige/open_cloud/blob/main/file/opencloud-linode.sh   

    var2=`echo $json | jq -r '.active_promotions[0].credit_remaining'`
    
    if [[ ${var2} == "null" ]];then
        create_linode
本来是100余额，返回，检测到该API存在问题，无法创建服务器！（2秒后返回）

    if [[ $json =~ "Invalid Token" ]];
    then
        echo "获取失败：令牌无效"
    else
        var1=`echo $json | jq -r '.email'`
        var2=`echo $json | jq -r '.active_promotions[0].credit_remaining'`
        echo -e  "电子邮箱：${var1}\n账号余额：${var2}\n有余额的账号才是正常的！"

**Comment by kyohan789** [comment]
2，https://github.com/LG-leige/open_cloud/blob/main/file/opencloud-digitalocean.sh
    json=`curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/account"`
    var1=`echo $json | jq -r '.account.status'`
    
    if [[ ${var1} == "active" ]];then
        create_do
    else
        echo -e  "检测到该API存在问题，无法创建服务器！（2秒后返回）"


此处，返回如果是warning，状态，也会出现 "检测到该API存在问题，无法创建服务器！（2秒后返回）"

**Comment by LG-leige** [comment]
目前已经更新到了新版本，已解决你提供的全部问题，感谢你的使用
