### ISSUE TITLE
使用aws开机脚本，选择地区报错

### ISSUE THREAD

**Issue by poluzhao** [LG-leige/open_cloud#2]
2022年 12月 18日 星期日 19:36:04 CST 正在进行AWS EC2 创建vm

parse error: Expected string key before ':' at line 1, column 4
请选择你的服务器所在地区（编号）:

添加API，测活没问题，选择地区的时候直接报错了，debian和centos都这样

**Comment by LG-leige** [comment]
你选择的VPS访问github出错了，所以没有获取到新的列表

**Comment by poluzhao** [comment]
换了几个vps，都一样，是因为AWS这几个字母大小写的原因么？我看到git里面有AWS目录和aws目录

**Comment by poluzhao** [comment]
改了AWS大写，解决了。另外，只能开t2和t3么？ 

 0.  t2 系列（除香港地区，其他可用免费套餐）
  1.  t3 系列（仅香港地区，可用免费套餐）

**Comment by LG-leige** [comment]
不用改，我后台改下路径就可以，现在只能开这些 如果有其他的话后续可能会更新吧
