### ISSUE TITLE
vultr地区不甚全面

### ISSUE THREAD

**Issue by qianchenmaofai** [LG-leige/open_cloud#3]
RT.
有新的地区，很好玩 建议加上

**Comment by LG-leige** [comment]
目前还没有脚本，暂时不考虑了

**Comment by sunianOvO** [comment]
> 

是正常的地区还是什么奇奇怪怪的业务？正常的你可以自己在开机的时候抓包或者电脑f12找到那个地区的代码自己放到脚本的地区代码里，或者你发到issues里让作者兼容？

**Comment by LG-leige** [comment]
文件里面有json你们可以自己提取下

 

发件人: sunianOvO ***@***.***> 
发送时间: 2022年12月21日 7:20
收件人: LG-leige/open_cloud ***@***.***>
抄送: Leige ***@***.***>; Comment ***@***.***>
主题: Re: [LG-leige/open_cloud] vultr地区不甚全面 (Issue #3)

 

是正常的地区还是什么奇奇怪怪的业务？正常的你可以自己在开机的时候抓包或者电脑f12找到那个地区的代码自己放到脚本的地区代码里，或者你发到issues里让作者兼容？

**Comment by LG-leige** [comment]
> > 
> 
> 正常的什么奇怪奇怪怪的业务？正常的你你在开机开机开机的的的时候时候时候时候抓包抓包或者电脑电脑电脑电脑电脑电脑或者或者或者或者或者或者找到找到找到找到找到找到找到找到找到找到那个那个那个那个地区的的代码自己自己自己放到放到放到脚本

目前能开的地区我都已经更新写上了的，应该是没有遗漏的，如果有遗漏欢迎补充
