### ISSUE TITLE
Lightsail 报错

### ISSUE THREAD

**Issue by lol4ever4ever** [LG-leige/open_cloud#5]
bash <(curl -Ls https://raw.githubusercontent.com/LG-leige/open_cloud/main/aws/opencloud-aws-Lightsail.sh)
/dev/fd/63: line 326: syntax error near unexpected token `}'
/dev/fd/63: line 326: `}'

**Comment by LG-leige** [comment]
这个问题已经解决了，但是上传到github curl到本地还是旧的文件，要等他缓存下去了才可以
